### ISSUE TITLE
Elastix 2.5

### ISSUE THREAD

**Issue by klistrod** [Loway/QueueMetricsHowTos#1]
![2015-12-28_145234er](https://cloud.githubusercontent.com/assets/8995233/12018384/e100af1c-ad72-11e5-91b8-36668304ea8a.png)
I did all the instructions but softphone and not logged.
Elastix 2.5 (64bit)

**Comment by l3nz** [comment]
Are you sure that your version of the browser and Asterisk and your SIP driver match the ones in the compatibility matrix?
